name: Parallel Browser Execution End-to-end tests
on: push
jobs:
  FireFox-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: firefox

      -name: Cypress Test Report - Firefox
        uses: actions/upload-artifact@v4
        with:
         name: Mocha Awesome HTML Report - Firefox
         path: cypress/reports/html

  Chrome-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          
      - name: Cypress Test Report - Chroome
        uses: actions/upload-artifact@v4
        with:
         name: Mocha Awesome HTML Report - Chrome Browser
         path: cypress/reports/html